#!/bin/sh
echo "***********************************"
echo "*          PowerCockpit           *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "PowerCockpit plugin installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
